services:
  - type: web
    name: iglesia-san-agustin
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24.19.0
      - key: DATABASE_URL
        fromDatabase:
          name: iglesia-san-agustin-db
          property: connectionString
      - key: ADMIN_PIN
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        value: mailto:admin@iglesia-san-agustin.onrender.com

databases:
  - name: iglesia-san-agustin-db
    plan: free
    databaseName: iglesia_san_agustin
    user: iglesia_admin
